name: chess_exercise_manager_flutter
description: Organise your favorite chess exercises and play them against the engine at its maximum strrength

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_abstract_chess_board:
    path: ../../Documents/Programmation/ProjetsPersos/Flutter/flutter_abstract_chess_board
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.4.3
  flutter_cupertino_localizations: ^1.0.1
  devicelocale: ^0.2.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - locale/i18n_en.json
    - locale/i18n_fr.json
    - locale/i18n_es.json